### PR TITLE
convert to html

### PR DESCRIPTION
**Pull request by donaldli2020**

### CODE REVIEW

**Comment by afkvido** [comment]
cant review this rn, imma see later

**Comment by donaldli2020** [comment]
i will need to do a lot of commits so it would be convenient to be collaborator

**Comment by afkvido** [comment]
> i will need to do a lot of commits so it would be convenient to be collaborator

ehhhh, you're quite trustworthy and I don't know what I'm doing, so screw it, I gave u collab ;)

**Review by afkvido — APPROVED** [review]
looks good to me, idk

**Pull request merged**
