### PR TITLE
favicon

### PR DESCRIPTION
**Pull request by yeeteeyt**

### CODE REVIEW

**Comment by afkvido** [comment]
Looks good to me! Thank you very much for your contribution, have a good day!

**Comment by afkvido** [comment]
I've also given you credit: https://github.com/afkvido/afkvido.github.io/commit/61e353c8807d8961bb132474d08c350896f590ae

**Comment by yeeteeyt** [comment]
Hi! could you merge the new pull request? I made a mistake in the file naming and left the original file title, so the element can´t link back to it. (I renamed the image to favicon.png, so that the site can source it)

**Comment by afkvido** [comment]
I did!

**Comment by afkvido** [comment]
ty

**Pull request merged**
