### PR TITLE
mind if i do this

### PR DESCRIPTION
**Pull request by donaldli2020**
# Description

### CODE REVIEW

**Review by afkvido — APPROVED** [review]
Hell yeah!

**Comment by afkvido** [comment]
Honestly, how'd u do that? 

Manually, or is there a beautifier for webmanifest?

**Comment by afkvido** [comment]
Anyways, tysm!

**Comment by donaldli2020** [comment]
manually

**Comment by afkvido** [comment]
Cool

**Comment by donaldli2020** [comment]
i just assumed it was json

**Comment by afkvido** [comment]
its kinda the same

**Pull request merged**
