### PR TITLE
issue

### PR DESCRIPTION
**Pull request by donaldli2020**
Doesn't let me use issues.

Open up the things in https://afkvido.github.io/
The content is broken.

### CODE REVIEW

**Comment by afkvido** [comment]
yup, it is.

working on it

**Comment by donaldli2020** [comment]
Oops, this was not supposed to be merged.

**Comment by donaldli2020** [comment]
I made a blank PR because Issues are disabled.

**Comment by afkvido** [comment]
> I made a blank PR because Issues are disabled.

oh ok

**Comment by afkvido** [comment]
@donaldli2020 I fixed it, check

**Comment by donaldli2020** [comment]
discord ico

**Comment by afkvido** [comment]
> 

what about it?

**Comment by afkvido** [comment]
yay I actually made issues

**Pull request merged**
